require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

platform :ios, '10.0'

target 'managedThenEject' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
  use_unimodules!(modules_paths: ['../node_modules'])

  # target 'managedThenEjectTests' do
  #   inherit! :complete
  #   # Pods for testing
  # end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

# target 'managedThenEject-tvOS' do
#   # Pods for managedThenEject-tvOS

#   target 'managedThenEject-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end
# end
